from WORLDS import WORLDS

worlddata_dot_c = """
// The following code was generated by the Red Pants Engine
// lets go baby

# include "worlds.h"
# include <SDL2/SDL.h>
# include <SDL2/SDL_image.h>

void world_load() {
"""

for name in WORLDS.keys():
    background = WORLDS[name]["background"]
    x_lock = WORLDS[name]["x_lock"]
    y_lock = WORLDS[name]["y_lock"]
    worlddata_dot_c += f"    add_world(\"{name}\", \"{background}\", {x_lock if x_lock is not None else 0}, {y_lock if y_lock is not None else 0});\n"
    for actor in WORLDS[name]["actors"]:
        worlddata_dot_c += f"    add_actor_to_world(\"{name}\", \"{actor}\");\n"
        
worlddata_dot_c += "}\n"

with open("worlddata.c", "w+") as f:
    f.write(worlddata_dot_c)

